spring:
  config:
    activate:
      on-profile:
        "qa"

build:
  version: "2.0"

accounts:
  message: "Welcome to EazyBank accounts related QA APIs "
  contactDetails:
    name: "Lowkey Felicilda - Lead QA"
    email: "contact@lowkey.com"
  onCallSupport:
    - (333) 555-1234
    - (333) 523-1345
