spring:
  config:
    activate:
      on-profile:
        "qa"

build:
  version:
    "1.0"

loans:
  message: "Welcome to EazyBanks Loans related to QA APIs"
  contactDetails:
    name: "Jerome Felicilda - Technical Architect"
    email: "contact@jerome.com"
  onSupportCall:
    - (969) 696-9696
    - (696) 969-6969
